groups:
  - name: km220
    rules:

      - alert: service_down
        expr: up{job="km220-actuator-node-1"} == 0
        for: 30s
        labels:
          severity: major
        annotations:
          summary: "Instance prod node-1 {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 30 seconds."
