global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  telegram_api_url: https://api.telegram.org

route:
    receiver: default-telegram
    continue: false
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h

receivers:
    - name: default-telegram
      telegram_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        api_url: https://api.telegram.org
        bot_token: 5688265658:AAG_B2tb1dp8dBtZH3FNPS2ytfDWpMCbJq4
        chat_id: -1001635023132
        message: '{{ template "telegram.default.message" . }}'
        parse_mode: HTML
templates: []