spring:
  datasource:
    url: jdbc:postgresql://10.1.0.6:5432/km220
  flyway:
    locations: 'classpath:db/migration/postgres/common,/db/migration/postgres/220stage'
    clean-on-validation-error: false
ewelink:
  email: km220.com@gmail.com
#  should be manually updated once per month
  useOAuth: true
  oAuth-token: '0bdd915829ca1ff116c09471112c49f38e5299a0xxxxx'
  oAuth-apiKey: 'e01b0584-0e12-4a67-95ec-8bf4cc87da85'

