ewelink:
  email: jasper.ua@gmail.com
  password: Nopassword1

spring:
  flyway:
    locations: 'classpath:db/migration/postgres/common,/db/migration/postgres/vlad'
    clean-on-validation-error: false

device:
  freeChargeSecs: 30