package com.km220.ewelink.error;

/**
 * Unexpected ewelink response on HTTP level.
 * Generated by checking HTTP response code.
 */
public class EwelinkHttpException extends EwelinkClientException {

  private final int responseCode;

  public EwelinkHttpException(final Throwable cause, final int responseCode) {
    super(cause);
    this.responseCode = responseCode;
  }

  public EwelinkHttpException(final String message, final int responseCode) {
    super(message);
    this.responseCode = responseCode;
  }

  public int getResponseCode() {
    return responseCode;
  }
}
