name: CI/CD Stage

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-depploy-on-stage:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: 220 build BE
        run: ./gradlew clean build -x test

      - name: 220 build FE
        run: cd src-js/react && npm i && npm run buildStage

      #      todo write function for all nodes
      #Node 1
      - name: 220 clean old deployments on stage-node-1
        uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf /220/**
          host: 157.90.254.213
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
      - name: 220 copy artifacts to stage-node-1
        uses: appleboy/scp-action@master
        with:
          host: 157.90.254.213
          username: root
          port: 22
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build/libs/220-km.com-0.0.1-SNAPSHOT.jar, src-js/react/build"
          target: "/220/"
      - name: 220 restart BE on stage-node-1
        uses: fifsky/ssh-action@master
        with:
          command: |
            systemctl restart run-220-be.service
          host: 157.90.254.213
          user: root
          key: ${{ secrets.PRIVATE_KEY}}

      #Node 2
#      - name: 220 clean old deployments on stage-node-2
#        uses: fifsky/ssh-action@master
#        with:
#          command: |
#            rm -rf /220/**
#          host: 157.90.252.84
#          user: root
#          key: ${{ secrets.PRIVATE_KEY}}
#      - name: 220 copy artifacts to stage-node-2
#        uses: appleboy/scp-action@master
#        with:
#          host: 157.90.252.84
#          username: root
#          port: 22
#          key: ${{ secrets.PRIVATE_KEY }}
#          source: "build/libs/220-km.com-0.0.1-SNAPSHOT.jar, src-js/react/build"
#          target: "/220/"
#      - name: 220 restart BE on stage-node-2
#        uses: fifsky/ssh-action@master
#        with:
#          command: |
#            systemctl restart run-220-be.service
#          host: 157.90.252.84
#          user: root
#          key: ${{ secrets.PRIVATE_KEY}}
  update-prometheus-on-stage:
    runs-on: 'ubuntu-latest'
    steps:
      - name: update-prometheus-on-stage
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /220/activecharge/ && git pull && docker-compose down --remove-orphans && docker-compose -f ./monitoring-docker-compose.yml up -d
          host: 157.90.252.84
          user: root
          key: ${{ secrets.PRIVATE_KEY}}
